site_name: NoRisk Client Server-Api Wiki
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - Payloads:
    - Toast Notifications: payloads/ToastPayload.md
    - Gamemode Override: payloads/GamemodePayload.md
    - Module Deactivation: payloads/ModuleDeactivatePayload.md
    - Action Wheel: payloads/WheelPayload.md
    - Input Prompts: payloads/InputbarPayload.md
    - Beacon Beams: payloads/BeaconBeamPayload.md
  - Utils: 
    - Check if Player plays NRC: utils/NRCPlayer.md

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://norisk.gg
      name: Website
    - icon: fontawesome/brands/discord
      link: https://discord.gg/noriskclient
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/NoRiskClient
      name: GitHub

copyright: Made with ❤️ by the NoRiskClient Team

extra_css:
  - css/index.css

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets